// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	alttendermint "github.com/tendermint/cosmos-rosetta-gateway/cosmos/launchpad/client/alttendermint"

	mock "github.com/stretchr/testify/mock"
)

// TendermintClient is an autogenerated mock type for the TendermintClient type
type TendermintClient struct {
	mock.Mock
}

// NetInfo provides a mock function with given fields:
func (_m *TendermintClient) NetInfo() (alttendermint.NetInfoResponse, error) {
	ret := _m.Called()

	var r0 alttendermint.NetInfoResponse
	if rf, ok := ret.Get(0).(func() alttendermint.NetInfoResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(alttendermint.NetInfoResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
