// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	openapi "github.com/tendermint/cosmos-rosetta-gateway/cosmos/launchpad/client/tendermint/generated"
)

// TendermintTxAPI is an autogenerated mock type for the TendermintTxAPI type
type TendermintTxAPI struct {
	mock.Mock
}

// BroadcastTxAsync provides a mock function with given fields: ctx, tx
func (_m *TendermintTxAPI) BroadcastTxAsync(ctx context.Context, tx string) (openapi.BroadcastTxResponse, *http.Response, error) {
	ret := _m.Called(ctx, tx)

	var r0 openapi.BroadcastTxResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) openapi.BroadcastTxResponse); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Get(0).(openapi.BroadcastTxResponse)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, string) *http.Response); ok {
		r1 = rf(ctx, tx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, tx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
