// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	openapi "github.com/tendermint/cosmos-rosetta-gateway/cosmos/launchpad/client/sdk/generated"
)

// CosmosTransactionsAPI is an autogenerated mock type for the CosmosTransactionsAPI type
type CosmosTransactionsAPI struct {
	mock.Mock
}

// TxsHashGet provides a mock function with given fields: ctx, hash
func (_m *CosmosTransactionsAPI) TxsHashGet(ctx context.Context, hash string) (openapi.TxQuery, *http.Response, error) {
	ret := _m.Called(ctx, hash)

	var r0 openapi.TxQuery
	if rf, ok := ret.Get(0).(func(context.Context, string) openapi.TxQuery); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Get(0).(openapi.TxQuery)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, string) *http.Response); ok {
		r1 = rf(ctx, hash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, hash)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
