#!/bin/bash

rm -rf rosetta/cosmos/launchpad/client/tendermint/mocks/
rm -rf rosetta/cosmos/launchpad/client/cosmos/mocks/

mockery --name ^Tendermint.*?API --dir rosetta/cosmos/launchpad --output rosetta/cosmos/launchpad/client/tendermint/mocks
mockery --name ^Cosmos.*?API --dir rosetta/cosmos/launchpad --output rosetta/cosmos/launchpad/client/cosmos/mocks
