#!/bin/bash

cosmos=cosmos/launchpad/client/cosmos/generated
cosmosyml=cosmos/launchpad/client/cosmos/swagger.yml

tendermint=cosmos/launchpad/client/tendermint/generated
tendermintyml=cosmos/launchpad/client/tendermint/openapi.yml

mkdir -p $cosmos
mkdir -p $tendermint

# https://openapi-generator.tech/
openapi-generator generate -g go -i $cosmosyml -o $cosmos
openapi-generator generate -g go -i $tendermintyml -o $tendermint
