#!/bin/bash

rm -rf cosmos/launchpad/client/tendermint/mocks/
rm -rf cosmos/launchpad/client/cosmos/mocks/

mockery --name ^Tendermint.*?API --dir cosmos/launchpad --output cosmos/launchpad/client/tendermint/mocks
mockery --name ^Cosmos.*?API --dir cosmos/launchpad --output cosmos/launchpad/client/cosmos/mocks
