#!/bin/bash

cosmos=rosetta/cosmos/launchpad/client/cosmos/generated
cosmosyml=rosetta/cosmos/launchpad/client/cosmos/swagger.yml

mkdir -p $cosmos

# https://openapi-generator.tech/
openapi-generator generate -g go -i $cosmosyml -o $cosmos
