// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	altsdk "github.com/tendermint/cosmos-rosetta-gateway/cosmos/launchpad/client/altsdk"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: request
func (_m *Client) Broadcast(request []byte) (*altsdk.BroadcastResp, error) {
	ret := _m.Called(request)

	var r0 *altsdk.BroadcastResp
	if rf, ok := ret.Get(0).(func([]byte) *altsdk.BroadcastResp); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*altsdk.BroadcastResp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
