// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	altsdk "github.com/tendermint/cosmos-rosetta-gateway/cosmos/launchpad/client/altsdk"

	mock "github.com/stretchr/testify/mock"

	types "github.com/tendermint/cosmos-rosetta-gateway/cosmos/launchpad/client/altsdk/types"
)

// SdkClient is an autogenerated mock type for the SdkClient type
type SdkClient struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: req
func (_m *SdkClient) Broadcast(req []byte) (*altsdk.BroadcastResp, error) {
	ret := _m.Called(req)

	var r0 *altsdk.BroadcastResp
	if rf, ok := ret.Get(0).(func([]byte) *altsdk.BroadcastResp); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*altsdk.BroadcastResp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthAccount provides a mock function with given fields: ctx, address
func (_m *SdkClient) GetAuthAccount(ctx context.Context, address string) (types.AccountResponse, error) {
	ret := _m.Called(ctx, address)

	var r0 types.AccountResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) types.AccountResponse); ok {
		r0 = rf(ctx, address)
	} else {
		r0 = ret.Get(0).(types.AccountResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
